version: '3'
services:
  mau:
    container_name: "sasaki_mau"
    shm_size: 1024mb
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $PWD:/home/MAU
    image: sasaki/mau:cuda116
    tty: true
