python3 MAU_run.py --dataset=mnist --config=mnist --batch_size=8
python3 MAU_run.py --dataset=mnist --config=mnist --batch_size=16
python3 MAU_run.py --dataset=mnist --config=mnist --batch_size=32
python3 MAU_run.py --dataset=mnist --config=mnist --batch_size=64
python3 MAU_run.py --dataset=mnist --config=mnist --batch_size=96
python3 MAU_run.py --dataset=aia211_5 --config=aia211_5 --batch_size=1
python3 MAU_run.py --dataset=aia211_5 --config=aia211_5 --batch_size=2
python3 MAU_run.py --dataset=aia211_5 --config=aia211_5 --batch_size=4
python3 MAU_run.py --dataset=aia211_5 --config=aia211_5 --batch_size=8
