import importlib
import argparse

def set_args():
    parser = argparse.ArgumentParser(description='MAU')
    parser.add_argument('--config',  type=str, required=True)
    parser.add_argument('--test',                   action='store_true')
    parser.add_argument('--dataset',                type=str)
    parser.add_argument('--data_train_path',        type=str)
    parser.add_argument('--data_val_path',          type=str)
    parser.add_argument('--data_test_path',         type=str)
    parser.add_argument('--input_length',           type=int)
    parser.add_argument('--real_length',            type=int)
    parser.add_argument('--total_length',           type=int)
    parser.add_argument('--img_height',             type=int)
    parser.add_argument('--img_width',              type=int)
    parser.add_argument('--sr_size',                type=int, help='Encoder-Decoderモデルの層の深さを決定')
    parser.add_argument('--in_channel',             type=int, help='入力チャンネル数')
    parser.add_argument('--out_channel',            type=int, help='出力チャンネル数')
    parser.add_argument('--patch_size',             type=int)
    parser.add_argument('--alpha',                  type=float )
    parser.add_argument('--model_name',             type=str)   
    parser.add_argument('--num_workers',            type=int)   
    parser.add_argument('--num_hidden',             type=int, help='MAUの入出力チャンネル数')   
    parser.add_argument('--num_layers',             type=int, help='MAUセルの深さ(スタック数)を決定')   
    parser.add_argument('--num_heads',              type=int)   
    parser.add_argument('--filter_size',            type=int)   
    parser.add_argument('--stride',                 type=int)   
    parser.add_argument('--time',                   type=int)   
    parser.add_argument('--time_stride',            type=int)   
    parser.add_argument('--tau',                    type=int)   
    parser.add_argument('--cell_mode',              type=str)   
    parser.add_argument('--model_mode',             type=str)  
    parser.add_argument('--lr',                     type=float) 
    parser.add_argument('--lr_decay',               type=float) 
    parser.add_argument('--delay_interval',         type=float) 
    parser.add_argument('--batch_size',             type=int)   
    parser.add_argument('--max_epoches',            type=int)   
    parser.add_argument('--sample_interval',        type=int)   
    parser.add_argument('--num_save_samples',       type=int)   
    parser.add_argument('--n_gpu',                  type=int)   
    parser.add_argument('--device',                 type=str)   
    parser.add_argument('--pretrained_model',       type=str)
    parser.add_argument('--save_dir',               type=str)
    parser.add_argument('--gen_frm_dir',            type=str)
    parser.add_argument('--scheduled_sampling',     type=bool)  
    parser.add_argument('--sampling_stop_iter',     type=int)  
    parser.add_argument('--sampling_start_value',   type=float) 
    parser.add_argument('--sampling_changing_rate', type=float) 
    args = parser.parse_args()

    configs = importlib.import_module(f"configs.{args.config}").configs
    args = configs(args)

    return args